### ISSUE TITLE
Issue with Beacon in React 15.x

### ISSUE THREAD

**Issue by sarates** [gilbarbara/react-joyride#361]
>Expected behavior

Beacon is visible after run:true

>Actual behavior

Beacon is added to DOM but always has visibility : hidden. If I changed it mannualy - next steps works fine. Seems it's issue with react version, because on 16.2.0 - all works. What version should I use for 15.5.4 or it possible to fix this for older version?

>Steps to reproduce the problem

>React version

15.5.4

>React-Joyride version

2.0.0-10

>Error stack

*If you are having UI issues, make sure to send a public URL or codesandbox example.*
![default](https://user-images.githubusercontent.com/4117293/39996404-0a1a1d40-5788-11e8-83be-fa078cc13f53.png)

**Comment by guytepper** [comment]
Same problem here using `react@15.5.4` and `joyride@2.0.0-10`

**Comment by sarates** [comment]
Temporary fixed by

`componentDidMount() {
    this.setState({ run: true }, () => {
      document.getElementById('react-joyride:0').getElementsByTagName("div")[0].children[1].style.visibility = 'visible';
    });
  }`

but I hope that this can be done in a civilized way

**Comment by varzock** [comment]
I think this is the reason why I can't restart the tour either. All the needed elements are in the DOM but their visibility is hidden and opacity 0.

**Comment by varzock** [comment]
I got it working with setTimeout and unmounting Joyride from DOM altogether. It timeouts in 300ms (which is the opacity / visibility animation duration) after which the component is unmounted.

After this when I restart Joyride tour it works without any setState errors since it mounts itself again.

**Comment by gilbarbara** [comment]
Fixed in `react-joyride@2.0.0-12`

**Comment by afrancht** [comment]
I'm still having this issue and I'm on `2.2.1`

![image](https://user-images.githubusercontent.com/19917183/87536341-40579900-c699-11ea-9d65-3964a2a78a4c.png)

![image](https://user-images.githubusercontent.com/19917183/87536407-5402ff80-c699-11ea-8df8-33486cdc5cb8.png)

**Comment by tenor-io** [comment]
Same problem here on 2.5.0

![image](https://user-images.githubusercontent.com/70980489/180310215-98359c5f-1817-4889-8326-1cb047e5d6ba.png)

**Comment by gilbarbara** [comment]
Hey!

This issue was about the beacon with React 15.x. If you're having problems with the floater, open a new issue with a codesnadbox example.
