### ISSUE TITLE
Position Mobile Landscape View

### ISSUE THREAD

**Issue by jerryf196** [gilbarbara/react-joyride#44]
Having this issue on mobile phones on landscape view. First step positions properly then I click on next and it scrolls to the element but the tooltip stays above.

In the _preventWindowOverflow() method I modified this line 571:
yPos: this._preventWindowOverflow(Math.ceil(placement.y), 'y', component.width, component.height),

to this:
yPos: placement.y,

Works fine. The question is does it need to run through this _preventWindowOverflow()? If yes then the logic is not working as expected.

This logic that calculates the position wrong

if (value + elHeight >= docHeight) {
     newValue = docHeight - elHeight - 15;
}

**Comment by gilbarbara** [comment]
Hey,

Can you please post your steps options? Isn't working for all steps or just some?

**Comment by jerryf196** [comment]
First off I have 3 elements on the page only. When in portrait mode all elements are visible to the page so that works fine. In landscape mode when page loads the first time it points to the first correct element. The second element does not work which points about another 100 pixels down and 3rd element works since it is within viewport. 

Steps:
1. Page loads tooltip pointing to correct element.
2.  Second element is not in view port click next and does not go to the second element as it does moves a few pixels down.
3. Third step is fine.

JSON Steps
`[
        { title: translator.translate('esl.first_time_use.step2.title1'),
          text: translator.translate('esl.first_time_use.step2.description1'),
          selector: '.add-document-button',
          position: 'top-left',
          name: 'firstTimeDismissEditTransaction',
          stepName: 'firstTimeAddDocument'
        },
        {
          title: translator.translate('esl.first_time_use.step2.title2'),
          text: translator.translate('esl.first_time_use.step2.description2'),
          selector: '.rolestype',
          position: 'top-left',
          name: 'firstTimeDismissEditTransaction',
          stepName: 'firstTimeAddSigner'
        },
        {
          title: translator.translate('esl.first_time_use.step2.title3'),
          text: translator.translate('esl.first_time_use.step2.description3'),
          selector: '.design-transaction-button',
          position: 'bottom-right',
          name: 'firstTimeDismissEditTransaction',
          stepName: 'firstTimeNext'
        }
      ],`

**Comment by jerryf196** [comment]
This condition returns me the wrong position

if (value + elHeight >= docHeight) {
newValue = docHeight - elHeight - 15;
}

My docHeight is 320
value is 296
elHeight is 148

The newValue returns about 140 which only scrolls 140 pixels. 

I need the original value from placement.y which is 400 something and works great!

**Comment by gilbarbara** [comment]
I fixed an issue with `scrollToSteps` in 2420d0c4c77216a9845951583126a6d0be3d19a4 and published as 1.3.3. Please try it and tell me if it works.

Can you try the demo and see if it works like you want?

`_preventWindowOverflow` is needed for sure. if you set a step's position to left or right and you are using a mobile device, the tooltip needs to be relocated.

**Comment by jerryf196** [comment]
Thanks for the quick reply. 

It doesn't fix the issue and not sure how that line fixes it. Like I said it's an issue with the condition in the method _preventWindowOverflow() that does not spit out the correct position that the tooltip needs to be at when advancing to the second step

if (value + elHeight >= docHeight) {
newValue = docHeight - elHeight - 15;
}

I actually included some designs of step1 and step2
![step1](https://cloud.githubusercontent.com/assets/197318/14460862/dc74da9a-008d-11e6-83dc-b82772db5f51.jpg)
![step2](https://cloud.githubusercontent.com/assets/197318/14460861/dc74d158-008d-11e6-9c4a-df0e8accf435.jpg)

**Comment by gilbarbara** [comment]
PR #48 merged and published as 1.3.4
Let me know if this works for you!

**Comment by gilbarbara** [comment]
Btw, which device/browser were you testing?

**Comment by jerryf196** [comment]
Hi,

Thanks for the quick reply and fix. I will test it later in the day.

For testing it was on an iphone 5. The screen shots that i supplied above are from the chrome emulator dev tools with iphone5 user agent setting. Usually I develop it on chrome and then once it works great I will test it on an iphone5 with chrome and safari

**Comment by jerryf196** [comment]
Beautiful! It works. Thanks for the help!
