### ISSUE TITLE
Controlled product tour popovers are not visible in React 18.1.0 using strict mode

### ISSUE THREAD

**Issue by Aidensaid** [gilbarbara/react-joyride#811]
## 🐛 Bug Report

Product tour popovers are not visible in React 18.1.0 using strict mode.

## To Reproduce

1. Open the [code sandbox](https://codesandbox.io/s/exciting-cohen-ynkqld?file=/src/_app.js)

2. Observe the product tour not visible

3. Comment out React.StrictMode

4. Observe the tour renders as expected

## Expected behavior

Expect the tour popover to be visible in the UI.

## Link to repl or repo (highly encouraged)

[code sandbox](https://codesandbox.io/s/exciting-cohen-ynkqld?file=/src/_app.js)

## Run `npx envinfo --system --binaries --npmPackages react-floater`

Paste the results here:

```bash
 System:
    OS: macOS 11.6.1
    CPU: (8) x64 Apple M1
    Memory: 174.59 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.2 - ~/.nvm/versions/node/v12.22.2/bin/node
    npm: 6.14.13 - ~/.nvm/versions/node/v12.22.2/bin/npm
```

**Comment by nicvickeryw** [comment]
Also experiencing this exact same issue

**Comment by victorst79** [comment]
Same config, same issue here. :disappointed:

**Comment by gilbarbara** [comment]
hey guys,

Please use the reactions (emoji) in the first comment instead of replying with the "same here".

**Comment by gilbarbara** [comment]
Fixed in 2.5.0
Thanks

**Comment by capucineSoum** [comment]
Hello,
I am still experiencing the issue with one step with the React Strict mode on. I have the 2.5.0 version of React Joyride.

Thank you

**Comment by gilbarbara** [comment]
Hey @capucineSoum 

Update to the `2.5.1`. If it still isn't working, create a new issue with a codesandbox.

**Comment by capucineSoum** [comment]
Hi @gilbarbara,
I did the update and the issue is still there but it is not linked to the strict mode as I was thinking. I will continue looking for a solution.
